@backend_HostAddress = https://localhost:5001

###
GET {{backend_HostAddress}}/api/products
Accept: application/json

###
POST {{backend_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "",
  "flavor": "",
  "price": -1
}

###
GET {{backend_HostAddress}}/api/error
