@backend_HostAddress = http://localhost:5000

###
# Get all products
GET {{backend_HostAddress}}/api/products
Accept: application/json

###
# Create a bad product (validation error)
POST {{backend_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "",
  "flavor": "",
  "price": -1
}

###
# Trigger an unhandled exception (global error handler)
GET {{backend_HostAddress}}/api/error
